### ISSUE TITLE
Convert template to jekyll

### ISSUE THREAD

**Issue by valterbarros** [valterbarros/valterbarros.github.io#5]
Only pass template to jekyll.

**Comment by rafa-acioly** [comment]
i can do this, you just want the `.html` file to `.md` with jekyll features?
you can also use this current template on github pages without jekyll...

**Comment by valterbarros** [comment]
Yes, I have a section with **static** posts, and if I add new posts I'll need update manually names and links. With jekyll I would add new posts and him will be append dynamically on site. Using this:

```
{% for posts in array %}
    {{ posts.description }} {{ posts.url }}
{% endfor %}
```

**Comment by rafa-acioly** [comment]
#6

**Comment by valterbarros** [comment]
hooooling shit, rafa I can't believe you convert all site to jekyll, this make me so much happy.

**Comment by rafa-acioly** [comment]
super easy mate! jekyll is love :heart: 
note that for `portfolio` you must set the category to `portfolio` and for default posts set `default`.

**Comment by valterbarros** [comment]
Nice, I'll run the project, thank you so much.
